/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleHorizontalLabel: typeof import('./pages/home/components/ArticleHorizontalLabel.vue')['default']
    BusinessContents: typeof import('./pages/home/components/BusinessContents.vue')['default']
    BusinessMap: typeof import('./pages/home/components/BusinessMap.vue')['default']
    CategoryBanner: typeof import('./pages/home/components/CategoryBanner.vue')['default']
    DataSlideGroups: typeof import('./pages/home/components/DataSlideGroups.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    RentalFrequency: typeof import('./pages/dashboard/overview/components/RentalFrequency.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    StatCardOverview: typeof import('./pages/dashboard/overview/components/StatCardOverview.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    ToggleDirection: typeof import('./components/blocks/ToggleDirection.vue')['default']
  }
}
